### PR TITLE
Feature#28 show employee status

### PR DESCRIPTION
**Pull request by elioflo**
# Description
What did you implement/Why did you implement this:
 - Modify the show employee view to show a better description of the employee status using active/inactive instead of true/false. To do this we create a custom field to display boolean as a string.
 - Modify the show employee view to show a better description of the employee presence using present/absent instead of true/false. To do this we create a custom field to display boolean as a string.
 - Disable the destroy/delete resource for Employee and Store.
 - Modify the order of attributes in the dashboards for employees and stores.

  ## Screenshots

The presence and status show as a string (Active/Inactive, Present/Absent). There's no destroy/delete button or link for employee and store. 
feature28

### CODE REVIEW

**Comment by kalixtosh** [comment]
Good job!

**Review by HopeSaurus — APPROVED** [review]
Looks good!

**Review by willcab — APPROVED** [review]
nice progress!

**Review by JuanequeX — APPROVED** [review]
LGTM

**Pull request merged**
